num_clients: 3
epochs: 5
batch_size: 64
learning_rate: 0.01
device: cpu # or 'cpu' if you're not using a GPU
fl_rounds: 2
eval_every_n_rounds: 1
clip_threshold: 1.0  # The maximum allowable L2 norm of the gradients
noise_multiplier: 0.1  # The amount of noise to add
